### ISSUE TITLE
建议对打卡时间加入适度延时

### ISSUE THREAD

**Issue by HEQH930** [HollowMan6/LZU-Auto-COVID-Health-Report#8]
如果单个用户在一个周期内的打卡时间均稳定在同一个时间点，甚至分秒不差，通过非常简单的筛查即可推断用户使用了机器打卡。建议能加入一定的随机时间量，在每日打卡动作执行后，延时1-20分钟完成打卡。

**Comment by HollowMan6** [comment]
谢谢建议！已经增加此功能并测试成功。目前对于单次运行，首次打卡开始等待时间在0-20分钟内随机浮动，若失败则在0-2分钟内随机浮动等待并再次尝试。

示例：https://open.work.weixin.qq.com/wwopen/mpnews?mixuin=pHhNDQAABwCobsHiAAAUAA&mfid=WW0314-uUeFpAAABwAJ9ZuBzOvb4A5FQYf59&idx=0&sn=35268f4e20f261ef83643f8c0700337b

**Comment by HollowMan6** [comment]
新版增加了判断，当用户是手动触发工作流时，不进行时间的随机浮动延迟打卡，方便用户0等待测试工作流配置
